//PACKAGE TOOL;
//
//IMPORT JAVA.IO.FILEREADER;
//
//IMPORT ORG.HIBERNATE.SESSION;
//IMPORT ORG.HIBERNATE.SESSIONFACTORY;
//IMPORT ORG.HIBERNATE.TRANSACTION;
//
//PUBLIC CLASS INIT {
//	
//	PUBLIC STATIC VOID MAIN(STRING ARGS[]) {
//
//		STRING LINE = "";
//
//		INT COUNT = 0;
//		SESSIONFACTORY FACTORY = HIBERNATEUTILS.GETSESSIONFACTORY();
//		SESSION SESSION = FACTORY.GETCURRENTSESSION();
//		TRANSACTION TX = NULL;
//		TRY {
//			TX = SESSION.BEGINTRANSACTION();
//			
//			// 1. 由"DATA/BOOKCOMPANY.DAT"逐筆讀入BOOKCOMPANY表格內的初始資料，
//			// 然後依序新增到BOOKCOMPANY表格中
//			TRY (
//				FILEREADER FR = NEW FILEREADER("DATA/BOOKCOMPANY.DAT"); 
//				BUFFEREDREADER BR = NEW BUFFEREDREADER(FR);
//			) {
//				WHILE ((LINE = BR.READLINE()) != NULL) {
//					IF (LINE.STARTSWITH(UTF8_BOM)) {
//						LINE = LINE.SUBSTRING(1);
//					}
//					STRING[] TOKEN = LINE.SPLIT("\\|");
//					STRING NAME = TOKEN[0];
//					STRING ADDRESS = TOKEN[1];
//					STRING URL = TOKEN[2];
//					COMPANYBEAN CB = NEW COMPANYBEAN(NULL, NAME, ADDRESS, URL);
//					SESSION.SAVE(CB);
//				}
//			} CATCH (IOEXCEPTION E) {
//				SYSTEM.ERR.PRINTLN("新建BOOKCOMPANY表格時發生IO例外: " + E.GETMESSAGE());
//			}
//			SESSION.FLUSH();
//			SYSTEM.OUT.PRINTLN("BOOKCOMPANY 資料新增成功");
//
//			FILE FILE = NEW FILE("DATA/BOOK.DAT");
//			// 2. 由"DATA/BOOK.DAT"逐筆讀入BOOK表格內的初始資料，然後依序新增
//			// 到BOOK表格中
//			TRY (
//				FILEINPUTSTREAM FIS = NEW FILEINPUTSTREAM(FILE);
//				INPUTSTREAMREADER ISR = NEW INPUTSTREAMREADER(FIS, "UTF8");
//				BUFFEREDREADER BR = NEW BUFFEREDREADER(ISR);
//			) {
//				WHILE ((LINE = BR.READLINE()) != NULL) {
//					SYSTEM.OUT.PRINTLN("LINE=" + LINE);
//					// 去除 UTF8_BOM: \UFEFF
//					IF (LINE.STARTSWITH(UTF8_BOM)) {
//						LINE = LINE.SUBSTRING(1);
//					}
//					STRING[] TOKEN = LINE.SPLIT("\\|");
//					BOOKBEAN BOOK = NEW BOOKBEAN();
//					BOOK.SETTITLE(TOKEN[0]);
//					BOOK.SETAUTHOR(TOKEN[1]);
//					BOOK.SETPRICE(DOUBLE.PARSEDOUBLE(TOKEN[2].TRIM()));
//					BOOK.SETDISCOUNT(DOUBLE.PARSEDOUBLE(TOKEN[3].TRIM()));
//					// BOOK.SETCOMPANYID(INTEGER.PARSEINT(TOKEN[4].TRIM()));
//					INT COMPANYID = INTEGER.PARSEINT(TOKEN[4].TRIM());
//					COMPANYBEAN CB = SESSION.GET(COMPANYBEAN.CLASS, COMPANYID);
//					BOOK.SETCOMPANYBEAN(CB);
//					// 讀取圖片檔
//					BLOB BLOB = SYSTEMUTILS2018.FILETOBLOB(TOKEN[5].TRIM());
//					BOOK.SETCOVERIMAGE(BLOB);
//					BOOK.SETFILENAME(SYSTEMUTILS2018.EXTRACTFILENAME(TOKEN[5].TRIM()));
//					BOOK.SETBOOKNO(TOKEN[6].TRIM());
//					BOOK.SETSTOCK(INTEGER.PARSEINT(TOKEN[7].TRIM()));
//					BOOK.SETCATEGORY(TOKEN[8].TRIM());
//					SESSION.SAVE(BOOK);
//					SYSTEM.OUT.PRINTLN("新增一筆BOOK紀錄成功");
//				}
//				// 印出資料新增成功的訊息
//				SESSION.FLUSH();
//				SYSTEM.OUT.PRINTLN("BOOK資料新增成功");
//			}
//
//			// 3. MEMBER表格
//			// 由"DATA/INPUT.TXT"逐筆讀入MEMBER表格內的初始資料，
//			// 然後依序新增到MEMBER表格中
//			TRY (
//				FILEINPUTSTREAM FIS = NEW FILEINPUTSTREAM("DATA/INPUT.TXT");
//				INPUTSTREAMREADER ISR0 = NEW INPUTSTREAMREADER(FIS, "UTF-8");
//				BUFFEREDREADER BR = NEW BUFFEREDREADER(ISR0);
//			) {
//				WHILE ((LINE = BR.READLINE()) != NULL) {
//					STRING[] SA = LINE.SPLIT("\\|");
//					MEMBERBEAN BEAN = NEW MEMBERBEAN();
//					BEAN.SETMEMBERID(SA[0]);
//					BEAN.SETNAME(SA[1]);
//					STRING PSWD = GLOBALSERVICE.GETMD5ENDOCING(GLOBALSERVICE.ENCRYPTSTRING(SA[2]));
//					BEAN.SETPASSWORD(PSWD);
//					BEAN.SETADDRESS(SA[3]);
//					BEAN.SETEMAIL(SA[4]);
//					BEAN.SETTEL(SA[5]);
//					BEAN.SETUSERTYPE(SA[6]);
//					BEAN.SETTOTALAMT(DOUBLE.PARSEDOUBLE(SA[7]));
//					BEAN.SETTS(NEW JAVA.SQL.TIMESTAMP(SYSTEM.CURRENTTIMEMILLIS()));
//					// --------------處理BLOB(圖片)欄位----------------
//					BLOB SB = SYSTEMUTILS2018.FILETOBLOB(SA[8]);
//					BEAN.SETMEMBERIMAGE(SB);
//					STRING IMAGEFILENAME = SA[8].SUBSTRING(SA[8].LASTINDEXOF("/") + 1);
//					BEAN.SETFILENAME(IMAGEFILENAME);
//					CLOB CLOB = SYSTEMUTILS2018.FILETOCLOB(SA[9]);
//					BEAN.SETCOMMENT(CLOB);
//					BEAN.SETUNPAID_AMOUNT(0.0);
//					SESSION.SAVE(BEAN);
//					COUNT++;
//					SYSTEM.OUT.PRINTLN("新增" + COUNT + "筆記錄:" + SA[1]);
//				}
//				SESSION.FLUSH();
//				SYSTEM.OUT.PRINTLN("MEMBER表格資料新增成功");
//			} CATCH (EXCEPTION EX) {
//				EX.PRINTSTACKTRACE();
//			}
//            TX.COMMIT();
//		} CATCH (EXCEPTION E) {
//			SYSTEM.ERR.PRINTLN("新建表格時發生例外: " + E.GETMESSAGE());
//			E.PRINTSTACKTRACE();
//			TX.ROLLBACK();
//		} 
//        FACTORY.CLOSE();
//	}
//	
//	
//
//}
